spring.application.name=web-admin-app
server.port=8080

# Redis Settings
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Central Service URL (Server 03)
central.service.url=http://localhost:8081/api
