spring.application.name=central-service
server.port=8081

# PostgreSQL Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/mission5_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Settings
spring.data.redis.host=localhost
spring.data.redis.port=6380
